// data.jsx — the five founding covenants.
//
// IMPORTANT: real covenant content must come from Kauri Tukere before publication.
// The body copy below is plausible scaffolding consistent with the project documentation,
// not a finished public declaration. It exists so the UI kit can render.

const COVENANTS = [
  {
    id: 'vouchmeapp',
    roman: 'I',
    title: 'VouchMeApp',
    creator: 'Kauri Tukere · Hero\u2019s Journey Creative',
    status: 'active',
    statusLabel: 'Active',
    summary: 'A peer-vouching platform built to slow the pace of digital trust and return it to people who actually know each other.',
    location: 'Wellington, Aotearoa New Zealand',
    version: 'v1.4',
    published: '03 Feb 2026',
    aiUse: 'AI was used during early-stage product writing to draft three variants of an onboarding screen. None of those variants were shipped. AI was also used as a coding assistant for boilerplate scaffolding in the authentication flow. No design work, brand work, or relationship copy was AI-generated.',
    labour: 'No human collaborator was displaced. The work that AI assisted with would otherwise have been done by the creator alone, more slowly. No outside writers, designers, or engineers were retained for the assisted work.',
    acknowledgements: ['The early users who agreed to vouch publicly during private beta.', 'The Aotearoa peer-trust research community whose work shaped the framing.'],
    beneficiaries: 'If VouchMeApp produces commercial value, ten percent of net proceeds will be directed to a community fund for digital trust research, named at the time of distribution.',
    valueIntent: 'No paid tier exists. If one is later introduced, this covenant will be amended in public and a new version recorded below.',
    versions: [
      { v: 'v1.4', date: '03 Feb 2026', note: 'Clarified onboarding-screen AI-use scope.' },
      { v: 'v1.3', date: '11 Nov 2025', note: 'Added value-sharing intent.' },
      { v: 'v1.0', date: '04 Aug 2025', note: 'Initial covenant published.' },
    ],
    withdrawn: false,
  },
  {
    id: 'fascia',
    roman: 'II',
    title: 'FASCIA',
    creator: 'Kauri Tukere',
    status: 'active',
    statusLabel: 'Active',
    summary: 'A long-form essay on connective tissue, told as a series of guided breathing observations.',
    location: 'Wellington, Aotearoa New Zealand',
    version: 'v1.2',
    published: '14 Mar 2026',
    aiUse: 'AI was used for transcript clean-up of recorded breathing-observation sessions, and for generating two background variations during layout exploration. Neither background was used in the final cut. The body of the essay was written by hand.',
    labour: 'No human transcriptionist was retained for the assisted clean-up. The writing itself was done by the creator. No editor, illustrator, or designer was substituted by AI.',
    acknowledgements: ['The breath-work practitioners whose teaching this essay rests on, named in the appendix.', 'The readers who reviewed three drafts before public release.'],
    beneficiaries: 'If FASCIA generates commercial value, a portion of proceeds will go to a fund for trauma-informed body-work education, named at the time of distribution.',
    valueIntent: 'FASCIA is published free to read. It will remain free to read.',
    versions: [
      { v: 'v1.2', date: '14 Mar 2026', note: 'Acknowledgements expanded.' },
      { v: 'v1.0', date: '02 Feb 2026', note: 'Initial covenant published.' },
    ],
    withdrawn: false,
  },
  {
    id: 'ho-and-the-baby-eater',
    roman: 'III',
    title: 'Ho and the Baby Eater',
    creator: 'Kauri Tukere',
    status: 'active',
    statusLabel: 'Active',
    summary: 'A short film whose visual concept was developed by hand. AI was permitted only in support roles, on a tight perimeter.',
    location: 'Wellington, Aotearoa New Zealand',
    version: 'v1.1',
    published: '21 Jan 2026',
    aiUse: 'AI was used for transcript clean-up of dialogue rehearsals and for two pieces of concept reference imagery during pre-production. No final-cut image, frame, or audio element was AI-generated. No voice was synthesised.',
    labour: 'No actor, voice artist, or composer was substituted by AI. The composer and the cast are credited in full in the film\u2019s end titles.',
    acknowledgements: ['The cast and crew, credited in full in the end titles.', 'The composer, whose original score is the only score used.'],
    beneficiaries: 'If the film generates commercial value, a portion of proceeds will be directed to a fund supporting independent Aotearoa filmmakers.',
    valueIntent: 'If a streaming platform later acquires the film, the platform\u2019s AI-training terms must be reviewed and recorded in this covenant before signing.',
    versions: [
      { v: 'v1.1', date: '21 Jan 2026', note: 'Pre-production AI-use scope clarified.' },
      { v: 'v1.0', date: '12 Dec 2025', note: 'Initial covenant published.' },
    ],
    withdrawn: false,
  },
  {
    id: 'aicovenants',
    roman: 'IV',
    title: 'aiCOVENANTS',
    creator: 'Kauri Tukere · Hero\u2019s Journey Creative',
    status: 'active',
    statusLabel: 'Active',
    summary: 'The covenant under which aiCOVENANTS itself is built. The platform is held to the same public standard it asks of its catalogue.',
    location: 'Wellington, Aotearoa New Zealand',
    version: 'v1.0',
    published: '04 Apr 2026',
    aiUse: 'AI assistants are used as planning, drafting, and coding collaborators in the building of aiCOVENANTS. ChatGPT (Aiea) acts as strategic co-architect. Codex acts as planner. Claude Code acts as executor. All product, brand, ethical, and scope decisions are made by the human owner. No covenant entry on this platform is AI-generated.',
    labour: 'AI is used in roles that would otherwise be performed by the owner alone, more slowly. No outside writer, designer, engineer, or strategist was retained and then replaced by AI on this project. No mass-onboarding pipeline exists.',
    acknowledgements: ['The founding catalogue creators, who agreed to publish their work under this model.', 'The readers and reviewers who shaped the brand foundations document.'],
    beneficiaries: 'If aiCOVENANTS later receives funding or generates revenue, a portion will be directed to public-interest research on AI and human labour, recorded in this covenant before distribution.',
    valueIntent: 'aiCOVENANTS will not introduce payments, tokens, or marketplace mechanics in the founding MVP. Any future paid tier will be recorded here, as a new version, before launch.',
    versions: [
      { v: 'v1.0', date: '04 Apr 2026', note: 'Initial covenant published alongside the founding catalogue.' },
    ],
    withdrawn: false,
  },
  {
    id: 'elevenlabs-voice',
    roman: 'V',
    title: 'ElevenLabs personal voice-use covenant request',
    creator: 'Kauri Tukere',
    status: 'pending',
    statusLabel: 'Pending',
    summary: 'A personal covenant requesting that no synthetic voice trained on this person\u2019s recorded speech be used commercially without an amended public declaration.',
    location: 'Wellington, Aotearoa New Zealand',
    version: 'v0.4',
    published: '02 Apr 2026',
    aiUse: 'This covenant is itself a request directed at the synthetic-voice platform ElevenLabs. It declares that any model trained on the creator\u2019s recorded voice, present or future, is to be considered out-of-scope for commercial deployment without an amended covenant version published here.',
    labour: 'The creator is a writer and presenter. A synthetic voice that sounded like the creator could displace future presenter work. This covenant exists to make that displacement public, not invisible.',
    acknowledgements: ['The voice-actor advocacy community whose framing has shaped this request.'],
    beneficiaries: 'Not applicable. This is a personal protective covenant, not a value-sharing arrangement.',
    valueIntent: 'No commercial use is granted under this covenant. A future amendment may grant scoped use; it would be recorded as a new version here, with explicit terms.',
    versions: [
      { v: 'v0.4', date: '02 Apr 2026', note: 'Pending review by ElevenLabs.' },
      { v: 'v0.1', date: '18 Mar 2026', note: 'Initial draft.' },
    ],
    withdrawn: false,
  },
];

window.COVENANTS = COVENANTS;
